Repository CovEducation/CovEd, pull requests merged in 2020-06, with the labels that each got.

#121 Optimized bundle sizes by removing duplicate css imports and fonts.
  .gitignore
  client/dist/index.html
  client/src/components/App.js
  client/src/components/modules/MentorFilter.js
  client/src/components/modules/NavBar.js
  client/src/components/pages/FAQ.js
  client/src/components/pages/FindAMentor.js
  client/src/components/pages/Homepage.js
  client/src/components/pages/Resources.js
  client/src/components/pages/SignIn.js
  client/src/components/pages/WhoWeAre.js
  client/src/index.js
Labels: performance

#119 Email mentor
  server/api.js
  server/sendEmail.js
  server/templates/match.html
Labels: enhancement, good first issue

#129 Fix race condition in #126
  client/src/components/modules/ProtectedPage.js
  client/src/components/pages/Profile.js
  client/src/providers/UserProvider.js
Labels: bug, good first issue
